name: Tanzawa-CI-Publish

on: [workflow_dispatch, workflow_call]

jobs:
  Publish:
    runs-on: [self-hosted, docker]
    permissions:
      contents: write
      packages: write
    timeout-minutes: 30
    container:
      image: ghcr.io/project-tsurugi/oltp-sandbox:ubuntu-22.04
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
      volumes:
        - ${{ vars.gradle_cache_dir }}:/root/.gradle
    defaults:
      run:
        shell: bash
    env:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
      GPR_USER: ${{ github.repository_owner }}
      GPR_KEY: ${{ secrets.GHCR_PAT }}

    steps:
      - name: Setup_Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GHA_PAT }}

      - name: Publish
        run: |
          ./gradlew -i tanzawa-core:showTsubakuroManifest clean publish

      - id: Create_Release
        name: Create_Release
        run: |
          ./gradlew -i distZip

          if [[ "${TANZAWA_VERSION}" == "SNAPSHOT" ]]; then
            _DELETE_OPTION=--cleanup-tag
          fi
          set -x
          gh release delete ${TANZAWA_VERSION} -y ${_DELETE_OPTION} --repo project-tsurugi/tanzawa || true
          gh release create ${TANZAWA_VERSION} modules/cli/build/distributions/tgsql.zip --title ${TANZAWA_VERSION} --prerelease --latest --repo project-tsurugi/tanzawa
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TANZAWA_VERSION: ${{ (github.ref_type == 'tag' && github.ref_name) || 'SNAPSHOT' }}
