name: Tanzawa-CI-Publish

on: [workflow_dispatch, workflow_call]
concurrency: ${{ github.workflow }}

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    env:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

    steps:
      - name: Setup_Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish
        run: |
          ./gradlew -i tanzawa-core:showTsubakuroManifest clean publish
        env:
          ST_OSSRH_USER: ${{ secrets.ST_OSSRH_USER }}
          ST_OSSRH_PASSWORD: ${{ secrets.ST_OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

      - id: Create_Release
        if: contains(github.ref, '/tags/')
        name: Create_Release
        run: |
          ./gradlew -i distZip
          set -x
          gh release create ${TANZAWA_VERSION} modules/cli/build/distributions/tgsql.zip --title ${TANZAWA_VERSION} --latest --repo project-tsurugi/tanzawa
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TANZAWA_VERSION: ${{ github.ref_name }}
