name: Tanzawa-CI-Release

on: [workflow_dispatch, workflow_call]
concurrency: ${{ github.workflow }}

jobs:
  Publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    env:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

    steps:
      - name: Setup_Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create_Release
        if: contains(github.ref, '/tags/')
        run: |
          cd modules/tgsql
          ../../gradlew -i distZip --warning-mode all
          cd -

          set -x
          gh release create ${TANZAWA_VERSION} modules/tgsql/cli/build/distributions/tgsql-${TANZAWA_VERSION}.zip --title ${TANZAWA_VERSION} --latest --repo project-tsurugi/tanzawa
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TANZAWA_VERSION: ${{ github.ref_name }}
